#if !canImport(ObjectiveC)
import XCTest

extension ElementaryFunctionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ElementaryFunctionTests = [
        ("testDouble", testDouble),
        ("testFloat", testFloat),
        ("testFloat80", testFloat80),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ElementaryFunctionTests.__allTests__ElementaryFunctionTests),
    ]
}
#endif
