#if !canImport(ObjectiveC)
import XCTest

extension ArithmeticBenchmarkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArithmeticBenchmarkTests = [
        ("testDivision", testDivision),
        ("testDivisionC", testDivisionC),
        ("testDivisionPoorScaling", testDivisionPoorScaling),
        ("testDivisionPoorScalingC", testDivisionPoorScalingC),
        ("testMultiplication", testMultiplication),
        ("testMultiplicationC", testMultiplicationC),
        ("testMultiplicationPoorScaling", testMultiplicationPoorScaling),
        ("testMultiplicationPoorScalingC", testMultiplicationPoorScalingC),
        ("testReciprocal", testReciprocal),
    ]
}

extension ArithmeticTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArithmeticTests = [
        ("testBaudinSmith", testBaudinSmith),
        ("testPolar", testPolar),
    ]
}

extension PropertyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PropertyTests = [
        ("testEquatableHashable", testEquatableHashable),
        ("testProperties", testProperties),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArithmeticBenchmarkTests.__allTests__ArithmeticBenchmarkTests),
        testCase(ArithmeticTests.__allTests__ArithmeticTests),
        testCase(PropertyTests.__allTests__PropertyTests),
    ]
}
#endif
