#if !canImport(ObjectiveC)
import XCTest

extension ComplexTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ComplexTests = [
        ("testEquality", testEquality),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ComplexTests.__allTests__ComplexTests),
    ]
}
#endif
