name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    name: Test
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "Swift Numerics"
      # https://github.com/apple/swift-numerics/issues/303
      license_header_check_enabled: false
      # https://github.com/apple/swift-numerics/issues/302
      format_check_enabled: false
